language: cpp
sudo: true
dist: trusty

matrix:
  include:
    - os: linux
      env: CMAKE_OPTIONS="-DCMAKE_RUNTIME_OUTPUT_DIRECTORY=bin -DOPENGL_ENABLED=OFF -DCeres_DIR=${TRAVIS_BUILD_DIR}/deps/ceres-solver/install/lib/cmake/Ceres -DQt5Core_DIR=/opt/qt54/lib/cmake/Qt5Core -DQt5OpenGL_DIR=/opt/qt54/lib/cmake/Qt5OpenGL" QT_QPA_PLATFORM=offscreen
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - cmake
            - build-essential
            - libeigen3-dev
            - libatlas-base-dev
            - libsuitesparse-dev
            - libfreeimage-dev
            - libgoogle-glog-dev
            - libgflags-dev
            - libglew-dev
    - os: osx
      env: CMAKE_OPTIONS="-DCMAKE_RUNTIME_OUTPUT_DIRECTORY=bin -DIPO_ENABLED=OFF -DQt5_DIR=/usr/local/opt/qt5/lib/cmake/Qt5 -DQt5Core_DIR=/usr/local/opt/qt5/lib/cmake/Qt5Core -DQt5OpenGL_DIR=/usr/local/opt/qt5/lib/cmake/Qt5OpenGL"

cache:
  directories:
    - ${TRAVIS_BUILD_DIR}/deps
    - ${TRAVIS_BUILD_DIR}/build

before_script:
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew tap homebrew/science
      brew install \
        cmake \
        eigen \
        glog \
        gflags \
        suite-sparse \
        ceres-solver \
        qt5 \
        glew || true
    fi
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      export DISPLAY=:99.0
      sh -e /etc/init.d/xvfb start
      sleep 3

      sudo add-apt-repository --yes ppa:beineri/opt-qt542-trusty
      sudo apt-get update -qq
      sudo apt-get -y install qt54base
      sudo apt-get -y install libopencv-dev

      cd ${TRAVIS_BUILD_DIR}
      echo https://${TRAVIS_USERNAME}:${TRAVIS_PASSWORD}@github.com > ~/.git-credentials
      git config --global user.name "${TRAVIS_USERNAME}"
      git config --global user.email "${TRAVIS_EMAIL}"
      git config --global credential.helper store
    fi

script:
  - cmake --version
  - cd build
  - rm -rf *
  - |
    if [[ -z "$(ls -A GSLAM)" ]]; then
      git clone ${TRAVIS_PULL}
    fi
  - cd SummerCamp2018Homework
  - git checkout ${TRAVIS_BRANCH}
  - mkdir -p build
  - cd build
  - pwd
  - bash ../scripts/Evaluate.sh -e ..
